# Generated by Django 4.1.7 on 2023-02-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('other', 'Разное'), ('smartphones', 'Смартфоны'), ('laptops', 'Ноутбуки'), ('refrigerators', 'Холодильники'), ('TV', 'Телевизоры')], default='other', max_length=20, verbose_name='Категория'),
        ),
    ]
